# Generated by Django 4.0.10 on 2023-09-09 04:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateField(default=datetime.date(2023, 9, 9), null=True)),
                ('isConfirm', models.IntegerField()),
                ('startDate', models.DateField(default=datetime.date(2023, 9, 9), null=True)),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('createDate', models.DateField(default=datetime.date(2023, 9, 9), null=True)),
                ('editingDate', models.DateField(default=datetime.date(2023, 9, 9), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kdv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('editingDate', models.DateField(default=datetime.date(2023, 9, 9), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Otv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('oldPrice', models.FloatField()),
                ('editingDate', models.DateField(default=datetime.date(2023, 9, 9), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('isActive', models.IntegerField()),
                ('creationDate', models.DateField(default=datetime.date(2023, 9, 9), null=True)),
                ('editingDate', models.DateField(default=datetime.date(2023, 9, 9), null=True)),
                ('price', models.FloatField()),
                ('previousPrice', models.FloatField()),
                ('discount', models.IntegerField()),
                ('deposit', models.FloatField()),
                ('categoryId', models.IntegerField()),
                ('isRented', models.IntegerField()),
                ('desc', models.CharField(max_length=500)),
                ('uavMedia', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('comRange', models.CharField(max_length=255)),
                ('payloadCapacity', models.FloatField()),
                ('ammunition', models.CharField(max_length=255)),
                ('endurance', models.FloatField()),
                ('travelSpeed', models.FloatField()),
                ('fuelCapacity', models.FloatField()),
                ('operationalAttitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('contactNumber', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('district', models.CharField(max_length=30, null=True)),
                ('identityNumber', models.CharField(max_length=250)),
                ('picturePath', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('createDate', models.DateField(default=datetime.date(2023, 9, 9), null=True)),
                ('editingDate', models.DateField(default=datetime.date(2023, 9, 9), null=True)),
                ('order', models.IntegerField()),
                ('typeId', models.IntegerField()),
                ('uavId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uav')),
            ],
        ),
        migrations.CreateModel(
            name='CartMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('cartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='kdvId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kdv'),
        ),
        migrations.AddField(
            model_name='cart',
            name='otvId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.otv'),
        ),
        migrations.AddField(
            model_name='cart',
            name='uavId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uav'),
        ),
        migrations.AddField(
            model_name='cart',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
