# Generated by Django 4.0.10 on 2023-09-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uav',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='uav',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='uav',
            name='stock',
        ),
    ]
