# Generated by Django 4.0.10 on 2023-09-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_uav_discount_remove_uav_isactive_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
